server:
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  ingress:
    enabled: false
controller:
  replicas: 1
repoServer:
  replicas: 1
applicationSet:
  replicas: 1
dex:
  enabled: false
redis:
  enabled: true
configs:
  cm:
    accounts.admin: apiKey
