---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-conn-secret
  namespace: dev
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgBG8Fx4rJZtyZ/+mxwDftZP4AjxkIWhDADpkXKmk8HBl3FYO27/2kvIbUB/Bz1GjEUvJcRUTd7tcP3q+9V26uik0TSGj8fxSIFtoLo9+lsMUf/PAWSWWljHH9uiz5sLnGeGtfy4tcNl9umj0zHqeYah59CiJ9W/6WE5tKAejhCPZt+3OvKos12WAZSQ5bp8lOsRf0/lHBF2xVZPRAYxqwGjBu5kOtKyPDuodfx9yfiAWdjGMAQN1u+EqD0xKh0x9vFEguNtc7M8sq0VIqtxTvYRysZ47z6P9hcslhkyR8dN0qHBfWOFFNfWy47XRE/SyiW6wPlsaLGg5Ykr5KJHvOb/6hI1JO3dQx6oUvMHSufR+0yvCvR7nGCZoU1JJaYoUW83c0e836pBTS3xOaUSrR0VYo1ioI8Nd32A+VwN3C6YNAsP6nbGScGk4JZoHVj8gUyWbIUkzpYS5/sxlphoE76qx3ZtDEQUajsEY4gV+BPJNSA1rGLNUMS2vQoTrIIVvGzSRly2gZktkjj0I8w6/yWQQnHzGymcXU071LWbvbSNcqS3QDC969eMY2VEJNmGikJ1BjCqKm2UpOyI5KoEDZb7f9vT2FwuT3+CukuBHuWgerm7dFhxR1FGIwGM7FN8GlEpzp1MCM8QFEolrOkddybzx9j/FNlhjWkFiEleS9NuLjkEZyaF2AtyQcYan4szcsPzfsaigGqYCgPKe1ZgV7TVAdpGnRnKV0/waLA1Vqih6eWcwUpo3AfZLzTuBtFg2Jl32azuriv7w0x6ibTMc4gbbgH0RCcFxYmprzOawMvmuFgXzzq9CPGu6LJLCIYjgHrdUvk3SYhIsulZpNU=
  template:
    metadata:
      creationTimestamp: null
      name: db-conn-secret
      namespace: dev
