controller:
  admin:
    username: admin
    password: admin
  serviceType: ClusterIP
  resources:
    limits:
      cpu: 800m
      memory: 2Gi

persistence:
  enabled: true
  size: 8Gi
  storageClass: nfs-client
  accessMode: ReadWriteMany

agent:
  enabled: true  # Agent'ı kapat