# nginx ingress controller için temel values.yaml
controller:
  replicaCount: 2
  service:
    type: LoadBalancer
  metrics:
    enabled: true
  admissionWebhooks:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
# Gerekirse nodeSelector, tolerations, affinity ekleyebilirsin 