primary:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 8Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

auth:
  username: appuser
  password: appsecret
  database: appdb
  postgresPassword: supersecret

service:
  type: ClusterIP

