apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fatih-aydin
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-fatih-aydin
  template:
    metadata:
      labels:
        app: app-fatih-aydin
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
      - name: app
        image: 20.71.249.196:8080/fatihh-app/app-v1:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-conn-secret
              key: ConnectionStrings__DefaultConnection
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi