apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-fatih-aydin-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: dev.fatihayd.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-fatih-aydin-service
            port:
              number: 5000